// PostgreSQL driver — used whenever DATABASE_URL is set (Supabase, Azure Database for
// PostgreSQL, or a local container). Presents the same execute() contract as db/sqlite.js, so
// services don't know which database they're talking to.
const fs = require("fs");
const { Pool } = require("pg");
const { tables, addedColumns, tableName, columnNames, primaryKeys } = require("../schema");

const COLUMN_NAMES = columnNames();
const PRIMARY_KEYS = primaryKeys();

// ---------- Connection ----------

const isLocalHost = (host) => ["localhost", "127.0.0.1", "::1"].includes(host);

// TLS: required for any remote database. With DATABASE_CA_CERT (a path to the provider's CA
// certificate, e.g. Supabase's "SSL certificate" download) the server's identity is verified;
// without it the connection is still encrypted but not verified, and we say so at startup.
const buildConfig = () => {
  const url = new URL(process.env.DATABASE_URL);
  // Read sslmode ourselves, then remove it so pg doesn't apply its own interpretation on top.
  // sslmode=disable is for private networks only (e.g. the docker compose network).
  const sslMode = url.searchParams.get("sslmode");
  url.searchParams.delete("sslmode");

  let ssl = false;
  let tlsNote = "no TLS (local)";
  if (sslMode === "disable") {
    tlsNote = "no TLS (sslmode=disable — private network only)";
  } else if (!isLocalHost(url.hostname)) {
    const caPath = process.env.DATABASE_CA_CERT;
    if (caPath) {
      ssl = { ca: fs.readFileSync(caPath, "utf8"), rejectUnauthorized: true };
      tlsNote = "TLS, certificate verified";
    } else {
      ssl = { rejectUnauthorized: false };
      tlsNote = "TLS, certificate NOT verified (set DATABASE_CA_CERT to verify)";
    }
  }

  return {
    config: {
      connectionString: url.toString(),
      ssl,
      max: Number(process.env.DATABASE_POOL_SIZE || 5),
      idleTimeoutMillis: 30_000,
      connectionTimeoutMillis: 10_000,
    },
    // Never log credentials: host and database name only
    description: `PostgreSQL (${url.hostname}:${url.port || 5432}${url.pathname}, ${tlsNote})`,
  };
};

const { config, description } = buildConfig();
const pool = new Pool(config);

// A dropped idle connection shouldn't crash the process; the pool replaces it
pool.on("error", (err) => console.error("[db] idle PostgreSQL connection error:", err.message));

// ---------- Schema ----------

const toPostgresDdl = (sql) =>
  sql.replace(/INTEGER PRIMARY KEY AUTOINCREMENT/g, "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");

// Any fixed number; every copy of the backend uses the same one
const SCHEMA_LOCK_ID = 7310001;

const init = async () => {
  // CREATE TABLE IF NOT EXISTS is not safe when two copies run it at the same moment (PostgreSQL
  // raises a duplicate-key error on its own catalog). Copies take turns: whoever holds this
  // advisory lock sets up the schema; the others wait, then find everything already there.
  const client = await pool.connect();
  try {
    await client.query("SELECT pg_advisory_lock($1)", [SCHEMA_LOCK_ID]);
    for (const sql of tables) {
      await client.query(toPostgresDdl(sql));
      // Supabase publishes the public schema through its own REST API. With row-level security on
      // and no policies, that API can read nothing; this backend connects as the table owner,
      // which RLS does not restrict. Harmless on plain PostgreSQL.
      await client.query(`ALTER TABLE ${tableName(sql)} ENABLE ROW LEVEL SECURITY`);
    }
    for (const [table, column, definition] of addedColumns) {
      await client.query(`ALTER TABLE ${table} ADD COLUMN IF NOT EXISTS ${column} ${definition}`);
    }
  } finally {
    await client.query("SELECT pg_advisory_unlock($1)", [SCHEMA_LOCK_ID]).catch(() => {});
    client.release();
  }
};

// ---------- Queries ----------

const normalizeValue = (value) => {
  if (value === undefined) return null;
  // Dates are stored as ISO-8601 text, exactly as in SQLite
  if (value instanceof Date) return value.toISOString();
  // Flags are INTEGER columns (0/1) in the shared schema
  if (typeof value === "boolean") return value ? 1 : 0;
  return value;
};

// "?" placeholders -> "$1, $2, ..." (no query in this codebase has a literal "?" inside a string)
const toPositional = (sql) => {
  let index = 0;
  return sql.replace(/\?/g, () => `$${++index}`);
};

// INSERTs report the new row's id, like SQLite's lastInsertRowid
const withReturning = (sql) => {
  const match = sql.match(/^\s*INSERT\s+INTO\s+(\w+)/i);
  if (!match || /\bRETURNING\b/i.test(sql)) return { sql, primaryKey: null };
  const primaryKey = PRIMARY_KEYS[match[1]];
  return primaryKey ? { sql: `${sql} RETURNING ${primaryKey}`, primaryKey } : { sql, primaryKey: null };
};

// PostgreSQL returns unquoted names in lower case (userid); restore UserID, and any "AS Alias"
const restoreNames = (sql) => {
  const aliases = {};
  for (const [, alias] of sql.matchAll(/\bAS\s+(\w+)/gi)) aliases[alias.toLowerCase()] = alias;

  return (row) => {
    const renamed = {};
    for (const [key, value] of Object.entries(row)) {
      renamed[aliases[key] || COLUMN_NAMES[key] || key] = value;
    }
    return renamed;
  };
};

// mysql2-style contract shared by both drivers:
//   SELECT            -> [rows]
//   INSERT/UPDATE/... -> [{ insertId, affectedRows }]
const execute = async (sql, params = []) => {
  const { sql: withReturn, primaryKey } = withReturning(sql);
  const result = await pool.query(toPositional(withReturn), params.map(normalizeValue));

  if (result.command === "SELECT") {
    return [result.rows.map(restoreNames(sql))];
  }

  return [
    {
      insertId: primaryKey ? result.rows[0]?.[primaryKey.toLowerCase()] : undefined,
      affectedRows: result.rowCount,
    },
  ];
};

const getConnection = async () => {
  const client = await pool.connect();
  return { release: () => client.release() };
};

module.exports = {
  dialect: "postgres",
  description,
  init,
  execute,
  getConnection,
  close: () => pool.end(),
};
